#!/usr/bin/python -u
# The -u makes output unbuffered, so it will show up immediately
# Austin Colcord and Nick Scheuring
import sys
from bridge import Bridge


def main():
    id = sys.argv[1]
    LAN = sys.argv[2:]
    my_bridge = Bridge(id, LAN)


if __name__ == "__main__":
    main()
