#!/usr/bin/python -u
# The -u makes output unbuffered, so it will show up immediately
import sys
from Bridge import Bridge


def main():
    id = sys.argv[1]
    LAN = sys.argv[2:]
    myBridge = Bridge(id, LAN)


if __name__ == "__main__":
    main()
